version: '3'
services:
  database:
    build:
      context: ./database
    ports:
      - "5432:5432"
    image: ws_4_db_image
    container_name: usersdb
  standalone:
    build:
      context: ./standalone
    image: ws_4_standalone_image
    container_name: standalone
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 8000:8000
  deploy:
    build:
     context: ./deploy
    image: ws_4_deploy_image
    container_name: deploy
    links:
      - database
    depends_on:
      - database
    ports:
      - 8080:8080
      - 4848:4848
      - 8181:8181


